shape_usda_name = {
    "AAD":"omniverse://localhost/MCE/3dIcons/AzureAAD_1.1.usd",
    "Resource_Group":"omniverse://localhost/MCE/3dIcons/Resource_Groups_2.1.usd",
    "Storage_account":"omniverse://localhost/MCE/3dIcons/StorageAccounts_2_8.usd",
    "App_Service":"omniverse://localhost/MCE/3dIcons/AppServices_1.2.usd",
    "Subscription":"omniverse://localhost/MCE/3dIcons/Subscriptions_1.3.usd",
    "API_Connection":"omniverse://localhost/MCE/3dIcons/API_Connection.usd",
    "API_Management_service":"omniverse://localhost/MCE/3dIcons/API_management_services_fix.usd",
    "App_Configuration":"omniverse://localhost/MCE/3dIcons/App-Configuration.usd",
    "App_Service_plan":"omniverse://localhost/MCE/3dIcons/app_service_plan_fix.usd",
    "App_Service":"omniverse://localhost/MCE/3dIcons/AppServices_1.2.usd",
    "Application_Insights":"omniverse://localhost/MCE/3dIcons/Application_Insights_4.0.usd",
    "Application_gateway":"omniverse://localhost/MCE/3dIcons/Application_Gateway.usd",
    "Automation_Account":"omniverse://localhost/MCE/3dIcons/automation_accounts_fix.usd",
    "Availability_test":"omniverse://localhost/MCE/3dIcons/Availability_Test.usd",
    "Azure_Bot":"omniverse://localhost/MCE/3dIcons/Web_App_Bot.usd",
    "Azure_Cosmos_DB_API_for_MongoDB_account":"omniverse://localhost/MCE/3dIcons/Azure_Cosmos_DB_API_MongoDB.usd",
    "Azure_Cosmos_DB_account":"omniverse://localhost/MCE/3dIcons/Azure_Cosmos_DB.usd",
    "Azure_Data_Explorer_Cluster":"omniverse://localhost/MCE/3dIcons/azure_data_explorer_clusters_fix.usd",
    "Azure_DevOps_organization":"omniverse://localhost/MCE/3dIcons/azure_devops_fix.usd",
    "Azure_Machine_Learning":"omniverse://localhost/MCE/3dIcons/Azure_Machine_Learning.usd",
    "Azure_Workbook":"omniverse://localhost/MCE/3dIcons/azure_workbook_fix.usd",
    "Bastion":"omniverse://localhost/MCE/3dIcons/Bastion.usd",
    "Cognitive_Service":"omniverse://localhost/MCE/3dIcons/Cognitive_Services.usd",
    "Container_registry":"omniverse://localhost/MCE/3dIcons/container_registries_fix.usd",
    "Data_Lake_Analytics":"omniverse://localhost/MCE/3dIcons/Data_Lake_Analytics_1.2.usd",
    "Data_Lake_Storage_Gen1":"omniverse://localhost/MCE/3dIcons/data_lake_storage_gen1_fix.usd",
    "Data_factory__V2_":"omniverse://localhost/MCE/3dIcons/data_factory_fix.usd",
    "Disk":"omniverse://localhost/MCE/3dIcons/Disk_1.0.usd",
    "DNS_zone":"omniverse://localhost/MCE/3dIcons/DNS_Zone.usd",
    "DNS_Zone":"omniverse://localhost/MCE/3dIcons/DNS_Zone.usd",
    "Event_Grid_System_Topic":"omniverse://localhost/MCE/3dIcons/event_grid_topics_fix.usd",
    "Event_Hubs_Namespace":"omniverse://localhost/MCE/3dIcons/events_hub_fix.usd",
    "Firewall_Policy":"omniverse://localhost/MCE/3dIcons/Firewall_Policy.usd",
    "Firewall":"omniverse://localhost/MCE/3dIcons/Firewall.usd",
    "Function_App":"omniverse://localhost/MCE/3dIcons/function_apps_fix.usd",
    "Image":"omniverse://localhost/MCE/3dIcons/image_fix.usd",
    "Key_vault":"omniverse://localhost/MCE/3dIcons/Key_Vaults_2.0.usd",
    "Kubernetes_service":"omniverse://localhost/MCE/3dIcons/kubernetess_services_fix.usd",
    "Language":"omniverse://localhost/MCE/3dIcons/Language_Understanding.usd",
    "Language_understanding":"omniverse://localhost/MCE/3dIcons/Language_Understanding.usd",
    "Load_balancer":"omniverse://localhost/MCE/3dIcons/load_balancer_fix.usd",
    "Log_Analytics_query_pack":"omniverse://localhost/MCE/3dIcons/Log_Analytics_Query_Pack.usd",
    "Log_Analytics_workspace":"omniverse://localhost/MCE/3dIcons/Log_Analytics_Workspace.usd",
    "Logic_App__Standard_":"omniverse://localhost/MCE/3dIcons/Logic_Apps_Std.usd",
    "Logic_app":"omniverse://localhost/MCE/3dIcons/Logic_apps_fix.usd",
    "Logic_apps_custom_connector":"omniverse://localhost/MCE/3dIcons/Logic_Apps_Custom_Connector.usd",
    "Managed_Identity":"omniverse://localhost/MCE/3dIcons/Managed_Identity.usd",
    "Managed_application":"omniverse://localhost/MCE/3dIcons/Managed_Identity.usd",
    "Network_Interface":"omniverse://localhost/MCE/3dIcons/network_interface_fix.usd",
    "Microsoft_Network_networkInterfaces":"omniverse://localhost/MCE/3dIcons/network_interface_fix.usd",
    "Network_Watcher":"omniverse://localhost/MCE/3dIcons/network_watcher_fix.usd",
    "Network_security_group":"omniverse://localhost/MCE/3dIcons/network_security_group_fix.usd",
    "Microsoft_Network_networkSecurityGroups" : "omniverse://localhost/MCE/3dIcons/network_security_group_fix.usd",
    "Power_BI_Embedded":"omniverse://localhost/MCE/3dIcons/Power_BI_Embedded_2.0.usd",
    "Private_DNS_zone":"omniverse://localhost/MCE/3dIcons/Private_DNS_Zone_2.0.usd",
    "Private_endpoint":"omniverse://localhost/MCE/3dIcons/Private_End_Point.usd",
    "Public_IP_address":"omniverse://localhost/MCE/3dIcons/public_ip_adresses_fix.usd",
    "Recovery_Services_vault":"omniverse://localhost/MCE/3dIcons/recovery_service_vault_fix.usd",
    "Restore_Point_Collection":"omniverse://localhost/MCE/3dIcons/Restore_Point_Collection_2.0.usd",
    "Runbook":"omniverse://localhost/MCE/3dIcons/Runbook.usd",
    "SQL_database":"omniverse://localhost/MCE/3dIcons/SQLDatabase.usd",
    "SQL_elastic_pool":"omniverse://localhost/MCE/3dIcons/SQL_Elastic_Pools.usd",
    "SQL_server":"omniverse://localhost/MCE/3dIcons/SQLServer.usd",
    "SQL_virtual_machine":"omniverse://localhost/MCE/3dIcons/sql_virtual_machine_fix.usd",
    "Search_service":"omniverse://localhost/MCE/3dIcons/search_services_fix.usd",
    "Service_Bus_Namespace":"omniverse://localhost/MCE/3dIcons/service_bus_fix.usd",
    "Service_Fabric_cluster":"omniverse://localhost/MCE/3dIcons/service-fabric-clusters_fix.usd",
    "Shared_dashboard":"omniverse://localhost/MCE/3dIcons/Shared_Dashboard.usd",
    "Snapshot":"omniverse://localhost/MCE/3dIcons/Snapshot.usd",
    "Solution":"omniverse://localhost/MCE/3dIcons/solution.usd",
    "Storage_account":"omniverse://localhost/MCE/3dIcons/StorageAccounts_2.8.usd",
    "Traffic_Manager_profile":"omniverse://localhost/MCE/3dIcons/traffic_manager_profiles_fix.usd",
    "Virtual_machine_scale_set":"omniverse://localhost/MCE/3dIcons/Virtual_Machines_Scale_Sets_2.0.usd",
    "Virtual_machine":"omniverse://localhost/MCE/3dIcons/Virtual_Machine_1.1.usd",
    "Virtual_network":"omniverse://localhost/MCE/3dIcons/Virtual_Network.usd",
    "Web_App_Bot":"omniverse://localhost/MCE/3dIcons/Web_App_Bot.usd",
    "Coat_Rack":"C:/Users/Gavin/Documents/AzureVerse/test/Coat_Rack__Bowler_Hat.usdz",
    "Observation_Chair":"omniverse://localhost/MCE/Nvidia-Ball-Chair/Nvidia-Ball-Chair.usd",
    "Leather_Jacket":"C:/Users/Gavin/Documents/AzureVerse/test/Leather_Jacket.usdz",
    "Rug_V4": "omniverse://localhost/MCE/3dIcons/RugV4.usd",
    "Neon_All_Resources":  "omniverse://localhost/MCE/NeonSigns/all_resources/all_resources.usd",
    "Neon_By_Group":  "omniverse://localhost/MCE/NeonSigns/resources_by_group/resources_by_group.usd",
    "Neon_By_Subscription":  "omniverse://localhost/MCE/NeonSigns/resources_by_cost/resources_by_cost.usd",
    "Neon_By_Location":  "omniverse://localhost/MCE/NeonSigns/resources_by_location/resources_by_location.usd",
    "Neon_Azure_Cloud":  "omniverse://localhost/MCE/NeonSigns/azure cloud/azure cloud.usd",
    "Microsoft_Web_certificates" :"omniverse://localhost/MCE/3dIcons/App_Service_Certificates.usd",
    "Microsoft_ClassicStorage_storageAccounts":"omniverse://localhost/MCE/3dIcons/StorageAccounts_2.8.usd",
    "Storage_account__classic_":"omniverse://localhost/MCE/3dIcons/StorageAccounts_2.8.usd",
    "microsoft_alertsmanagement_smartDetectorAlertRules": "omniverse://localhost/MCE/3dIcons/Alerts.usd",
    "Microsoft_KeyVault_vaults":"omniverse://localhost/MCE/3dIcons/Key_Vaults_2.0.usd",
    "Microsoft_Storage_storageAccounts" : "omniverse://localhost/MCE/3dIcons/StorageAccounts_2.8.usd",
    "Microsoft_Network_dnszones" : "omniverse://localhost/MCE/3dIcons/DNS_Zone.usd",
    "Microsoft_Web_sites": "omniverse://localhost/MCE/3dIcons/AppServices_1.2.usd",
    "Microsoft_Web_serverFarms" : "omniverse://localhost/MCE/3dIcons/app_service_plan_fix.usd",
    "Microsoft_Network_networkWatchers" : "omniverse://localhost/MCE/3dIcons/network_watcher_fix.usd",
    "Microsoft_OperationalInsights_workspaces" : "omniverse://localhost/MCE/3dIcons/Log_Analytics_Workspace.usd",
    "Microsoft_OperationsManagement_solutions" : "omniverse://localhost/MCE/3dIcons/solution.usd",
    "microsoft_insights_autoscalesettings" : "",
    "microsoft_visualstudio_account" :"omniverse://localhost/MCE/3dIcons/azure_devops_fix.usd",
    "Microsoft_Migrate_moveCollections" : "",
    "microsoft_insights_actiongroups" : "",
    "Microsoft_Insights_components":"omniverse://localhost/MCE/3dIcons/Application_Insights_4.0.usd",
    "Microsoft_Portal_dashboards" : "omniverse://localhost/MCE/3dIcons/Shared_Dashboard.usd",
    "Microsoft_ContainerRegistry_registries": "omniverse://localhost/MCE/3dIcons/container_registries_fix.usd",
    "Microsoft_RecoveryServices_vaults":"omniverse://localhost/MCE/3dIcons/recovery_service_vault_fix.usd",
    "Microsoft_DevTestLab_schedules": ""
}



