
shape_usda_name = {
    "AAD": "omniverse://localhost/Resources/3dIcons/AzureAAD_1.1.usd",
    "Resource Group": "omniverse://localhost/Resources/3dIcons/Resource_Groups_2.0.usd",
    "Storage account": "omniverse://localhost/Resources/3dIcons/StorageAccounts_2_8.usd",
    "App Service": "omniverse://localhost/Resources/3dIcons/AppServices_1_2.usd",
    "Subscription": "omniverse://localhost/Resources/3dIcons/Subscriptions_1_3.usd",
    "API Connection" : "omniverse://localhost/Resources/3dIcons/API_Connection.usd",
    "API Management service" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "App Configuration" : "omniverse://localhost/Resources/3dIcons/App-Configuration.usd",
    "App Service plan" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "App Service" : "omniverse://localhost/Resources/3dIcons/AppServices_1_2.usd",
    "Application Insights" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Application gateway" : "omniverse://localhost/Resources/3dIcons/Application_Gateway.usd",
    "Automation Account" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Availability test": "omniverse://localhost/Resources/3dIcons/Availability_Test_1.3.usd",
    "Azure Cosmos DB API for MongoDB account" : "omniverse://localhost/Resources/3dIcons/Azure_Cosmos_DB_API_MongoDB.usd",
    "Azure Cosmos DB account" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Azure Data Explorer Cluster" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Azure DevOps organization" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Azure Machine Learning" : "omniverse://localhost/Resources/3dIcons/Azure_Machine_Learning.usd",
    "Azure Workbook" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Bastion" : "omniverse://localhost/Resources/3dIcons/Bastion.usd",
    "Cognitive Service" : "omniverse://localhost/Resources/3dIcons/Cognitive_Services.usd",
    "Container registry" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Data Lake Analytics" : "omniverse://localhost/Resources/3dIcons/Data_Lake_Analytics_1.2.usd",
    "Data Lake Storage Gen1" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Data factory (V2)" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Disk" : "omniverse://localhost/Resources/3dIcons/Disk_1.0.usd",
    "DNS Zone" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Event Grid System Topic" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Event Hubs Namespace" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Firewall Policy" : "omniverse://localhost/Resources/3dIcons/Firewall_Policy.usd",
    "Firewall" : "omniverse://localhost/Resources/3dIcons/Firewall.usd",
    "Function App" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Image" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Key vault" : "omniverse://localhost/Resources/3dIcons/Key_Vaults.usd",
    "Kubernetes service" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Language understanding" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Load balancer" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Log Analytics query pack" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Log Analytics workspace" : "omniverse://localhost/Resources/3dIcons/Log_Analytics_Workspace.usd",
    "Logic App (Standard)" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Logic app" : "omniverse://localhost/Resources/3dIcons/Logic_Apps_Std.usd",
    "Logic apps custom connector" : "omniverse://localhost/Resources/3dIcons/Logic_Apps_Custom_Connector.usd",
    "Managed Identity" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Network Interface" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Network Watcher" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Network security group" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Power BI Embedded" : "omniverse://localhost/Resources/3dIcons/Powe_BI_Embedded.usd",
    "Private DNS zone" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Private endpoint" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Public IP address" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Recovery Services vault" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Restore Point Collection" : "omniverse://localhost/Resources/3dIcons/Restore_Point_Collection.usd",
    "Runbook" : "omniverse://localhost/Resources/3dIcons/Runbook.usd",
    "SQL database" : "omniverse://localhost/Resources/3dIcons/SQLServer_6_0.usd",
    "SQL elastic pool" : "omniverse://localhost/Resources/3dIcons/SQL_Elastic_Pools.usd",
    "SQL server" : "omniverse://localhost/Resources/3dIcons/SQLServer.usd",
    "SQL virtual machine" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Search service" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Service Bus Namespace" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Service Fabric cluster" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Shared dashboard" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Snapshot" : "omniverse://localhost/Resources/3dIcons/Snapshot.usd",
    "Solution" : "omniverse://localhost/Resources/3dIcons/Solution_1.3.usd",
    "Storage account" : "omniverse://localhost/Resources/3dIcons/StorageAccounts_2.8.usd",
    "Traffic Manager profile" : "omniverse://localhost/Resources/3dIcons/cube.usd",
    "Virtual machine scale set" : "omniverse://localhost/Resources/3dIcons/Virtual_Machines_Scale_Sets.usd",
    "Virtual machine" : "omniverse://localhost/Resources/3dIcons/Virtual_Machine.usd",
    "Virtual network" : "omniverse://localhost/Resources/3dIcons/Virtual_Network.usd",
    "Web App Bot" : "omniverse://localhost/Resources/3dIcons/cube.usd",
}


