
shape_usda_name = {
    "AAD": "omniverse://localhost/MCE/cube.usda",
    "Resource Group": "omniverse://localhost/MCE/cube.usda",
    "Storage account": "omniverse://localhost/MCE/cube.usda",
    "App Service": "omniverse://localhost/MCE/cube.usda",
    "Subscription": "omniverse://localhost/MCE/cube.usda",
    "API Connection" : "omniverse://localhost/MCE/cube.usda",
    "API Management service" : "omniverse://localhost/MCE/cube.usda",
    "App Configuration" : "omniverse://localhost/MCE/cube.usda",
    "App Service plan" : "omniverse://localhost/MCE/cube.usda",
    "App Service" : "omniverse://localhost/MCE/cube.usda",
    "Application Insights" : "omniverse://localhost/MCE/cube.usda",
    "Application gateway" : "omniverse://localhost/MCE/cube.usda",
    "Automation Account" : "omniverse://localhost/MCE/cube.usda",
    "Availability test": "omniverse://localhost/MCE/cube.usda",
    "Azure Cosmos DB API for MongoDB account" : "omniverse://localhost/MCE/cube.usda",
    "Azure Cosmos DB account" : "omniverse://localhost/MCE/cube.usda",
    "Azure Data Explorer Cluster" : "omniverse://localhost/MCE/cube.usda",
    "Azure DevOps organization" : "omniverse://localhost/MCE/cube.usda",
    "Azure Machine Learning" : "omniverse://localhost/MCE/cube.usda",
    "Azure Workbook" : "omniverse://localhost/MCE/cube.usda",
    "Bastion" : "omniverse://localhost/MCE/cube.usda",
    "Cognitive Service" : "omniverse://localhost/MCE/cube.usda",
    "Container registry" : "omniverse://localhost/MCE/cube.usda",
    "Data Lake Analytics" : "omniverse://localhost/MCE/cube.usda",
    "Data Lake Storage Gen1" : "omniverse://localhost/MCE/cube.usda",
    "Data factory (V2)" : "omniverse://localhost/MCE/cube.usda",
    "Disk" : "omniverse://localhost/MCE/cube.usda",
    "Event Grid System Topic" : "omniverse://localhost/MCE/cube.usda",
    "Event Hubs Namespace" : "omniverse://localhost/MCE/cube.usda",
    "Firewall Policy" : "omniverse://localhost/MCE/cube.usda",
    "Firewall" : "omniverse://localhost/MCE/cube.usda",
    "Function App" : "omniverse://localhost/MCE/cube.usda",
    "Image" : "omniverse://localhost/MCE/cube.usda",
    "Key vault" : "omniverse://localhost/MCE/cube.usda",
    "Kubernetes service" : "omniverse://localhost/MCE/cube.usda",
    "Language understanding" : "omniverse://localhost/MCE/cube.usda",
    "Load balancer" : "omniverse://localhost/MCE/cube.usda",
    "Log Analytics query pack" : "omniverse://localhost/MCE/cube.usda",
    "Log Analytics workspace" : "omniverse://localhost/MCE/cube.usda",
    "Logic App (Standard)" : "omniverse://localhost/MCE/cube.usda",
    "Logic app" : "omniverse://localhost/MCE/cube.usda",
    "Logic apps custom connector" : "omniverse://localhost/MCE/cube.usda",
    "Managed Identity" : "omniverse://localhost/MCE/cube.usda",
    "Network Interface" : "omniverse://localhost/MCE/cube.usda",
    "Network Watcher" : "omniverse://localhost/MCE/cube.usda",
    "Network security group" : "omniverse://localhost/MCE/cube.usda",
    "Power BI Embedded" : "omniverse://localhost/MCE/cube.usda",
    "Private DNS zone" : "omniverse://localhost/MCE/cube.usda",
    "Private endpoint" : "omniverse://localhost/MCE/cube.usda",
    "Public IP address" : "omniverse://localhost/MCE/cube.usda",
    "Recovery Services vault" : "omniverse://localhost/MCE/cube.usda",
    "Restore Point Collection" : "omniverse://localhost/MCE/cube.usda",
    "Runbook" : "omniverse://localhost/MCE/cube.usda",
    "SQL database" : "omniverse://localhost/MCE/cube.usda",
    "SQL elastic pool" : "omniverse://localhost/MCE/cube.usda",
    "SQL server" : "omniverse://localhost/MCE/cube.usda",
    "SQL virtual machine" : "omniverse://localhost/MCE/cube.usda",
    "Search service" : "omniverse://localhost/MCE/cube.usda",
    "Service Bus Namespace" : "omniverse://localhost/MCE/cube.usda",
    "Service Fabric cluster" : "omniverse://localhost/MCE/cube.usda",
    "Shared dashboard" : "omniverse://localhost/MCE/cube.usda",
    "Snapshot" : "omniverse://localhost/MCE/cube.usda",
    "Solution" : "omniverse://localhost/MCE/cube.usda",
    "Storage account" : "omniverse://localhost/MCE/cube.usda",
    "Traffic Manager profile" : "omniverse://localhost/MCE/cube.usda",
    "Virtual machine scale set" : "omniverse://localhost/MCE/cube.usda",
    "Virtual machine" : "omniverse://localhost/MCE/cube.usda",
    "Virtual network" : "omniverse://localhost/MCE/cube.usda",
    "Web App Bot" : "omniverse://localhost/MCE/cube.usda",
}


